export const post = [
  {
    userId: 1,
    id: 101,
    title: "Lorem Ipsum 1",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    userId: 2,
    id: 102,
    title: "Lorem Ipsum 2",
    body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    userId: 3,
    id: 103,
    title: "Lorem Ipsum 3",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    userId: 4,
    id: 104,
    title: "Lorem Ipsum 4",
    body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  },
  {
    userId: 5,
    id: 105,
    title: "Lorem Ipsum 5",
    body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 6,
    id: 106,
    title: "Lorem Ipsum 6",
    body: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 7,
    id: 107,
    title: "Lorem Ipsum 7",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  },
  {
    userId: 8,
    id: 108,
    title: "Lorem Ipsum 8",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  },
  {
    userId: 9,
    id: 109,
    title: "Lorem Ipsum 9",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
  },
  {
    userId: 10,
    id: 110,
    title: "Lorem Ipsum 10",
    body: "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    userId: 11,
    id: 111,
    title: "Lorem Ipsum 11",
    body: "Et harum quidem rerum facilis est et expedita distinctio.",
  },
  {
    userId: 12,
    id: 112,
    title: "Lorem Ipsum 12",
    body: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  },
  {
    userId: 13,
    id: 113,
    title: "Lorem Ipsum 13",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
  },
  {
    userId: 14,
    id: 114,
    title: "Lorem Ipsum 14",
    body: "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  },
  {
    userId: 15,
    id: 115,
    title: "Lorem Ipsum 15",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    userId: 16,
    id: 116,
    title: "Lorem Ipsum 16",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    userId: 17,
    id: 117,
    title: "Lorem Ipsum 17",
    body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  },
  {
    userId: 18,
    id: 118,
    title: "Lorem Ipsum 18",
    body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 19,
    id: 119,
    title: "Lorem Ipsum 19",
    body: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 20,
    id: 120,
    title: "Lorem Ipsum 20",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  },
  {
    userId: 21,
    id: 121,
    title: "Lorem Ipsum 21",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  },
  {
    userId: 22,
    id: 122,
    title: "Lorem Ipsum 22",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
  },
  {
    userId: 23,
    id: 123,
    title: "Lorem Ipsum 23",
    body: "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    userId: 24,
    id: 124,
    title: "Lorem Ipsum 24",
    body: "Et harum quidem rerum facilis est et expedita distinctio.",
  },
  {
    userId: 25,
    id: 125,
    title: "Lorem Ipsum 25",
    body: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  },
  {
    userId: 26,
    id: 126,
    title: "Lorem Ipsum 26",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
  },
  {
    userId: 27,
    id: 127,
    title: "Lorem Ipsum 27",
    body: "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  },
  {
    userId: 28,
    id: 128,
    title: "Lorem Ipsum 28",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    userId: 29,
    id: 129,
    title: "Lorem Ipsum 29",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    userId: 30,
    id: 130,
    title: "Lorem Ipsum 30",
    body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  },
  {
    userId: 31,
    id: 131,
    title: "Lorem Ipsum 31",
    body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 32,
    id: 132,
    title: "Lorem Ipsum 32",
    body: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 33,
    id: 133,
    title: "Lorem Ipsum 33",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  },
  {
    userId: 34,
    id: 134,
    title: "Lorem Ipsum 34",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  },
  {
    userId: 35,
    id: 135,
    title: "Lorem Ipsum 35",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
  },
  {
    userId: 36,
    id: 136,
    title: "Lorem Ipsum 36",
    body: "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    userId: 37,
    id: 137,
    title: "Lorem Ipsum 37",
    body: "Et harum quidem rerum facilis est et expedita distinctio.",
  },
  {
    userId: 38,
    id: 138,
    title: "Lorem Ipsum 38",
    body: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  },
  {
    userId: 39,
    id: 139,
    title: "Lorem Ipsum 39",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
  },
  {
    userId: 40,
    id: 140,
    title: "Lorem Ipsum 40",
    body: "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  },
  {
    userId: 41,
    id: 141,
    title: "Lorem Ipsum 41",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    userId: 42,
    id: 142,
    title: "Lorem Ipsum 42",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    userId: 43,
    id: 143,
    title: "Lorem Ipsum 43",
    body: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
  },
  {
    userId: 44,
    id: 144,
    title: "Lorem Ipsum 44",
    body: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 45,
    id: 145,
    title: "Lorem Ipsum 45",
    body: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    userId: 46,
    id: 146,
    title: "Lorem Ipsum 46",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  },
  {
    userId: 47,
    id: 147,
    title: "Lorem Ipsum 47",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  },
  {
    userId: 48,
    id: 148,
    title: "Lorem Ipsum 48",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
  },
  {
    userId: 49,
    id: 149,
    title: "Lorem Ipsum 49",
    body: "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
  },
  {
    userId: 50,
    id: 150,
    title: "Lorem Ipsum 50",
    body: "Et harum quidem rerum facilis est et expedita distinctio.",
  },
  {
    userId: 51,
    id: 151,
    title: "Lorem Ipsum 51",
    body: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  },
  {
    userId: 52,
    id: 152,
    title: "Lorem Ipsum 52",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
  },
  {
    userId: 53,
    id: 153,
    title: "Lorem Ipsum 53",
    body: "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  },
  {
    userId: 54,
    id: 154,
    title: "Lorem Ipsum 54",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    userId: 55,
    id: 155,
    title: "Lorem Ipsum 55",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
  },
];

// export default post;
